language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true
env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="
addons:
  apt:
    packages:
    - git

before_install:
  # Set up anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda

  # commit message of current head of RMG-tests = SHA-ID of RMG-Py commit to be tested.
  - REV=$(git log --format=%B -n 1 HEAD)
  
  - cd ..


  - git clone https://github.com/ReactionMechanismGenerator/RMG-Py.git
  - export RMG=`pwd`/RMG-Py
  - export PYTHONPATH=$RMG:$PYTHONPATH

  - git clone https://github.com/ReactionMechanismGenerator/RMG-database.git

  - cd RMG-Py
  - git checkout $REV

install:
  - conda env create 
  - source activate rmg_env
  - make

script: 
  # go to RMG-tests folder:
  - cd $TRAVIS_BUILD_DIR
  - make ARGS="eg1" run
  - make ARGS="eg3" run
  - make ARGS="eg5" run
  - make ARGS="eg6" run
  - make ARGS="eg7" run

cache:
  pip: true
  apt: true
  # directories:
  #   - $HOME/anaconda/pkgs
