language: python
sudo: false
python:
  - "2.7"

before_install: 
  - . ./before_install.sh
  - . ./color_define.sh

install:
  - . ./install.sh
  - . ./version_summary.sh
  - chmod +x run.sh

after_failure:
  - . ./after_failure.sh

jobs:
  include:
    - stage: build
      script:
        - . ./compile.sh
    - stage: test
      script:
        - ./run.sh rmg/aromatics no
        - ./run.sh rmg/nitrogen no
        - ./run.sh rmg/sulfur no
    - script:
        - ./run.sh rmg/oxidation no
        - ./run.sh rmg/liquid_oxidation no
        - ./run.sh rmg/superminimal no
    - script:
        - ./run.sh examples/eg1 no
        - ./run.sh examples/eg5 no
    - stage: finish
      script: skip
      after_success:
        - . ./after_success.sh

cache:
  directories:
    - $TRAVIS_BUILD_DIR/code

branches:
  only:
    - /^rmgpy-.*$/
    - /^rmgdb-.*$/
    - /^rmgpydb-.*$/
