language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true
env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="
addons:
  apt:
    packages:
    - git

before_install: 
  - chmod +x before_install.sh
  - . ./before_install.sh

install: 
  - chmod +x install.sh
  - . ./install.sh
  - chmod +x version_summary.sh
  - . ./version_summary.sh
  - chmod +x run.sh

script: 
  - ./run.sh eg1
  - ./run.sh eg3
  - ./run.sh eg5
  - ./run.sh eg6
  - ./run.sh eg7
  - ./run.sh NC
  - ./run.sh MCH
  - ./run.sh solvent_hexane
  - ./run.sh methane

after_script:
  - chmod +x after_install.sh
  - . ./after_install.sh
  
cache:
  pip: true
  apt: true
  # directories:
  #   - $HOME/anaconda/pkgs

branches:
  only:
    - /^rmgpy-.*$/
    - /^rmgdb-.*$/